export const COUNTRY_CODE_WITH_FLAGS = [
    { id: "+93", code: "+93", name: "Afghanistan", flag: "🇦🇫" },
    { id: "+355", code: "+355", name: "Albania", flag: "🇦🇱" },
    { id: "+213", code: "+213", name: "Algeria", flag: "🇩🇿" },
    { id: "+1684", code: "+1684", name: "American Samoa", flag: "🇦🇸" },
    { id: "+376", code: "+376", name: "Andorra", flag: "🇦🇩" },
    { id: "+244", code: "+244", name: "Angola", flag: "🇦🇴" },
    { id: "+1264", code: "+1264", name: "Anguilla", flag: "🇦🇮" },
    { id: "+672", code: "+672", name: "Antarctica", flag: "🇦🇶" },
    { id: "+54", code: "+54", name: "Argentina", flag: "🇦🇷" },
    { id: "+374", code: "+374", name: "Armenia", flag: "🇦🇲" },
    { id: "+297", code: "+297", name: "Aruba", flag: "🇦🇼" },
    { id: "+61", code: "+61", name: "Australia", flag: "🇦🇺" },
    { id: "+43", code: "+43", name: "Austria", flag: "🇦🇹" },
    { id: "+994", code: "+994", name: "Azerbaijan", flag: "🇦🇿" },
    { id: "+1242", code: "+1242", name: "Bahamas", flag: "🇧🇸" },
    { id: "+973", code: "+973", name: "Bahrain", flag: "🇧🇭" },
    { id: "+880", code: "+880", name: "Bangladesh", flag: "🇧🇩" },
    { id: "+1246", code: "+1246", name: "Barbados", flag: "🇧🇧" },
    { id: "+375", code: "+375", name: "Belarus", flag: "🇧🇾" },
    { id: "+32", code: "+32", name: "Belgium", flag: "🇧🇪" },
    { id: "+501", code: "+501", name: "Belize", flag: "🇧🇿" },
    { id: "+229", code: "+229", name: "Benin", flag: "🇧🇯" },
    { id: "+975", code: "+975", name: "Bhutan", flag: "🇧🇹" },
    { id: "+591", code: "+591", name: "Bolivia", flag: "🇧🇴" },
    { id: "+387", code: "+387", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
    { id: "+267", code: "+267", name: "Botswana", flag: "🇧🇼" },
    { id: "+55", code: "+55", name: "Brazil", flag: "🇧🇷" },
    { id: "+1284", code: "+1284", name: "British Virgin Islands", flag: "🇻🇬" },
    { id: "+673", code: "+673", name: "Brunei Darussalam", flag: "🇧🇳" },
    { id: "+359", code: "+359", name: "Bulgaria", flag: "🇧🇬" },
    { id: "+226", code: "+226", name: "Burkina Faso", flag: "🇧🇫" },
    { id: "+257", code: "+257", name: "Burundi", flag: "🇧🇮" },
    { id: "+855", code: "+855", name: "Cambodia", flag: "🇰🇭" },
    { id: "+237", code: "+237", name: "Cameroon", flag: "🇨🇲" },
    { id: "+1", code: "+1", name: "Canada", flag: "🇨🇦" },
    { id: "+238", code: "+238", name: "Cape Verde", flag: "🇨🇻" },
    { id: "+1345", code: "+1345", name: "Cayman Islands", flag: "🇰🇾" },
    { id: "+236", code: "+236", name: "Central African Republic", flag: "🇨🇫" },
    { id: "+56", code: "+56", name: "Chile", flag: "🇨🇱" },
    { id: "+86", code: "+86", name: "China", flag: "🇨🇳" },
    { id: "+61", code: "+61", name: "Christmas Island", flag: "🇨🇽" },
    { id: "+61", code: "+61", name: "Cocos Islands", flag: "🇨🇨" },
    { id: "+57", code: "+57", name: "Colombia", flag: "🇨🇴" },
    { id: "+269", code: "+269", name: "Comoros", flag: "🇰🇲" },
    { id: "+242", code: "+242", name: "Congo", flag: "🇨🇬" },
    { id: "+243", code: "+243", name: "Congo (Democratic Republic)", flag: "🇨🇩" },
    { id: "+682", code: "+682", name: "Cook Islands", flag: "🇨🇰" },
    { id: "+506", code: "+506", name: "Costa Rica", flag: "🇨🇷" },
    { id: "+225", code: "+225", name: "Ivory Coast", flag: "🇨🇮" },
    { id: "+385", code: "+385", name: "Croatia", flag: "🇭🇷" },
    { id: "+53", code: "+53", name: "Cuba", flag: "🇨🇺" },
    { id: "+599", code: "+599", name: "Curaçao", flag: "🇨🇼" },
    { id: "+357", code: "+357", name: "Cyprus", flag: "🇨🇾" },
    { id: "+420", code: "+420", name: "Czech Republic", flag: "🇨🇿" },
    { id: "+45", code: "+45", name: "Denmark", flag: "🇩🇰" },
    { id: "+253", code: "+253", name: "Djibouti", flag: "🇩🇯" },
    { id: "+1767", code: "+1767", name: "Dominica", flag: "🇩🇲" },
    { id: "+1849", code: "+1849", name: "Dominican Republic", flag: "🇩🇴" },
    { id: "+670", code: "+670", name: "East Timor", flag: "🇹🇱" },
    { id: "+593", code: "+593", name: "Ecuador", flag: "🇪🇨" },
    { id: "+20", code: "+20", name: "Egypt", flag: "🇪🇬" },
    { id: "+503", code: "+503", name: "El Salvador", flag: "🇸🇻" },
    { id: "+240", code: "+240", name: "Equatorial Guinea", flag: "🇬🇶" },
    { id: "+291", code: "+291", name: "Eritrea", flag: "🇪🇷" },
    { id: "+372", code: "+372", name: "Estonia", flag: "🇪🇪" },
    { id: "+251", code: "+251", name: "Ethiopia", flag: "🇪🇹" },
    { id: "+500", code: "+500", name: "Falkland Islands", flag: "🇫🇰" },
    { id: "+298", code: "+298", name: "Faroe Islands", flag: "🇫🇴" },
    { id: "+679", code: "+679", name: "Fiji", flag: "🇫🇯" },
    { id: "+358", code: "+358", name: "Finland", flag: "🇫🇮" },
    { id: "+33", code: "+33", name: "France", flag: "🇫🇷" },
    { id: "+594", code: "+594", name: "French Guiana", flag: "🇬🇫" },
    { id: "+689", code: "+689", name: "French Polynesia", flag: "🇵🇫" },
    { id: "+241", code: "+241", name: "Gabon", flag: "🇬🇦" },
    { id: "+220", code: "+220", name: "Gambia", flag: "🇬🇲" },
    { id: "+995", code: "+995", name: "Georgia", flag: "🇬🇪" },
    { id: "+49", code: "+49", name: "Germany", flag: "🇩🇪" },
    { id: "+233", code: "+233", name: "Ghana", flag: "🇬🇭" },
    { id: "+350", code: "+350", name: "Gibraltar", flag: "🇬🇮" },
    { id: "+30", code: "+30", name: "Greece", flag: "🇬🇷" },
    { id: "+299", code: "+299", name: "Greenland", flag: "🇬🇱" },
    { id: "+1473", code: "+1473", name: "Grenada", flag: "🇬🇩" },
    { id: "+502", code: "+502", name: "Guatemala", flag: "🇬🇹" },
    { id: "+224", code: "+224", name: "Guinea", flag: "🇬🇳" },
    { id: "+245", code: "+245", name: "Guinea-Bissau", flag: "🇬🇼" },
    { id: "+595", code: "+595", name: "Paraguay", flag: "🇵🇾" },
    { id: "+509", code: "+509", name: "Haiti", flag: "🇭🇹" },
    { id: "+504", code: "+504", name: "Honduras", flag: "🇭🇳" },
    { id: "+852", code: "+852", name: "Hong Kong", flag: "🇭🇰" },
    { id: "+36", code: "+36", name: "Hungary", flag: "🇭🇺" },
    { id: "+354", code: "+354", name: "Iceland", flag: "🇮🇸" },
    { id: "+91", code: "+91", name: "India", flag: "🇮🇳" },
    { id: "+62", code: "+62", name: "Indonesia", flag: "🇮🇩" },
    { id: "+98", code: "+98", name: "Iran", flag: "🇮🇷" },
    { id: "+964", code: "+964", name: "Iraq", flag: "🇮🇶" },
    { id: "+353", code: "+353", name: "Ireland", flag: "🇮🇪" },
    { id: "+972", code: "+972", name: "Israel", flag: "🇮🇱" },
    { id: "+39", code: "+39", name: "Italy", flag: "🇮🇹" },
    { id: "+1", code: "+1", name: "Jamaica", flag: "🇯🇲" },
    { id: "+81", code: "+81", name: "Japan", flag: "🇯🇵" },
    { id: "+962", code: "+962", name: "Jordan", flag: "🇯🇴" },
    { id: "+7", code: "+7", name: "Kazakhstan", flag: "🇰🇿" },
    { id: "+254", code: "+254", name: "Kenya", flag: "🇰🇪" },
    { id: "+686", code: "+686", name: "Kiribati", flag: "🇰🇮" },
    { id: "+965", code: "+965", name: "Kuwait", flag: "🇰🇼" },
    { id: "+996", code: "+996", name: "Kyrgyzstan", flag: "🇰🇬" },
    { id: "+856", code: "+856", name: "Laos", flag: "🇱🇦" },
    { id: "+371", code: "+371", name: "Latvia", flag: "🇱🇻" },
    { id: "+961", code: "+961", name: "Lebanon", flag: "🇱🇧" },
    { id: "+266", code: "+266", name: "Lesotho", flag: "🇱🇸" },
    { id: "+231", code: "+231", name: "Liberia", flag: "🇱🇷" },
    { id: "+218", code: "+218", name: "Libya", flag: "🇱🇾" },
    { id: "+423", code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
    { id: "+370", code: "+370", name: "Lithuania", flag: "🇱🇹" },
    { id: "+352", code: "+352", name: "Luxembourg", flag: "🇱🇺" },
    { id: "+853", code: "+853", name: "Macau", flag: "🇲🇴" },
    { id: "+389", code: "+389", name: "Macedonia", flag: "🇲🇰" },
    { id: "+261", code: "+261", name: "Madagascar", flag: "🇲🇬" },
    { id: "+265", code: "+265", name: "Malawi", flag: "🇲🇼" },
    { id: "+60", code: "+60", name: "Malaysia", flag: "🇲🇾" },
    { id: "+960", code: "+960", name: "Maldives", flag: "🇲🇻" },
    { id: "+223", code: "+223", name: "Mali", flag: "🇲🇱" },
    { id: "+356", code: "+356", name: "Malta", flag: "🇲🇹" },
    { id: "+692", code: "+692", name: "Marshall Islands", flag: "🇲🇭" },
    { id: "+596", code: "+596", name: "Martinique", flag: "🇲🇶" },
    { id: "+222", code: "+222", name: "Mauritania", flag: "🇲🇷" },
    { id: "+230", code: "+230", name: "Mauritius", flag: "🇲🇺" },
    { id: "+262", code: "+262", name: "Mayotte", flag: "🇾🇹" },
    { id: "+52", code: "+52", name: "Mexico", flag: "🇲🇽" },
    { id: "+691", code: "+691", name: "Micronesia", flag: "🇫🇲" },
    { id: "+373", code: "+373", name: "Moldova", flag: "🇲🇩" },
    { id: "+377", code: "+377", name: "Monaco", flag: "🇲🇨" },
    { id: "+976", code: "+976", name: "Mongolia", flag: "🇲🇳" },
    { id: "+382", code: "+382", name: "Montenegro", flag: "🇲🇪" },
    { id: "+1664", code: "+1664", name: "Montserrat", flag: "🇲🇸" },
    { id: "+212", code: "+212", name: "Morocco", flag: "🇲🇦" },
    { id: "+258", code: "+258", name: "Mozambique", flag: "🇲🇿" },
    { id: "+95", code: "+95", name: "Myanmar", flag: "🇲🇲" },
    { id: "+264", code: "+264", name: "Namibia", flag: "🇳🇦" },
    { id: "+674", code: "+674", name: "Nauru", flag: "🇳🇷" },
    { id: "+977", code: "+977", name: "Nepal", flag: "🇳🇵" },
    { id: "+31", code: "+31", name: "Netherlands", flag: "🇳🇱" },
    { id: "+64", code: "+64", name: "New Zealand", flag: "🇳🇿" },
    { id: "+505", code: "+505", name: "Nicaragua", flag: "🇳🇮" },
    { id: "+227", code: "+227", name: "Niger", flag: "🇳🇪" },
    { id: "+234", code: "+234", name: "Nigeria", flag: "🇳🇬" },
    { id: "+683", code: "+683", name: "Niue", flag: "🇳🇺" },
    { id: "+850", code: "+850", name: "North Korea", flag: "🇰🇵" },
    { id: "+47", code: "+47", name: "Norway", flag: "🇳🇴" },
    { id: "+968", code: "+968", name: "Oman", flag: "🇴🇲" },
    { id: "+92", code: "+92", name: "Pakistan", flag: "🇵🇰" },
    { id: "+680", code: "+680", name: "Palau", flag: "🇵🇼" },
    { id: "+970", code: "+970", name: "Palestinian Territory", flag: "🇵🇸" },
    { id: "+507", code: "+507", name: "Panama", flag: "🇵🇦" },
    { id: "+675", code: "+675", name: "Papua New Guinea", flag: "🇵🇬" },
    { id: "+51", code: "+51", name: "Peru", flag: "🇵🇪" },
    { id: "+63", code: "+63", name: "Philippines", flag: "🇵🇭" },
    { id: "+48", code: "+48", name: "Poland", flag: "🇵🇱" },
    { id: "+351", code: "+351", name: "Portugal", flag: "🇵🇹" },
    { id: "+1", code: "+1", name: "Puerto Rico", flag: "🇵🇷" },
    { id: "+974", code: "+974", name: "Qatar", flag: "🇶🇦" },
    { id: "+40", code: "+40", name: "Romania", flag: "🇷🇴" },
    { id: "+7", code: "+7", name: "Russia", flag: "🇷🇺" },
    { id: "+250", code: "+250", name: "Rwanda", flag: "🇷🇼" },
    { id: "+685", code: "+685", name: "Samoa", flag: "🇼🇸" },
    { id: "+378", code: "+378", name: "San Marino", flag: "🇸🇲" },
    { id: "+239", code: "+239", name: "São Tomé and Príncipe", flag: "🇸🇹" },
    { id: "+966", code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
    { id: "+221", code: "+221", name: "Senegal", flag: "🇸🇳" },
    { id: "+381", code: "+381", name: "Serbia", flag: "🇷🇸" },
    { id: "+248", code: "+248", name: "Seychelles", flag: "🇸🇨" },
    { id: "+232", code: "+232", name: "Sierra Leone", flag: "🇸🇱" },
    { id: "+65", code: "+65", name: "Singapore", flag: "🇸🇬" },
    { id: "+421", code: "+421", name: "Slovakia", flag: "🇸🇰" },
    { id: "+386", code: "+386", name: "Slovenia", flag: "🇸🇮" },
    { id: "+677", code: "+677", name: "Solomon Islands", flag: "🇸🇧" },
    { id: "+252", code: "+252", name: "Somalia", flag: "🇸🇴" },
    { id: "+27", code: "+27", name: "South Africa", flag: "🇿🇦" },
    { id: "+82", code: "+82", name: "South Korea", flag: "🇰🇷" },
    { id: "+34", code: "+34", name: "Spain", flag: "🇪🇸" },
    { id: "+94", code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
    { id: "+249", code: "+249", name: "Sudan", flag: "🇸🇩" },
    { id: "+597", code: "+597", name: "Suriname", flag: "🇸🇷" },
    { id: "+47", code: "+47", name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
    { id: "+268", code: "+268", name: "Eswatini", flag: "🇸🇿" },
    { id: "+46", code: "+46", name: "Sweden", flag: "🇸🇪" },
    { id: "+41", code: "+41", name: "Switzerland", flag: "🇨🇭" },
    { id: "+963", code: "+963", name: "Syria", flag: "🇸🇾" },
    { id: "+886", code: "+886", name: "Taiwan", flag: "🇹🇼" },
    { id: "+992", code: "+992", name: "Tajikistan", flag: "🇹🇯" },
    { id: "+255", code: "+255", name: "Tanzania", flag: "🇹🇿" },
    { id: "+66", code: "+66", name: "Thailand", flag: "🇹🇭" },
    { id: "+228", code: "+228", name: "Togo", flag: "🇹🇬" },
    { id: "+690", code: "+690", name: "Tokelau", flag: "🇹🇰" },
    { id: "+676", code: "+676", name: "Tonga", flag: "🇹🇴" },
    { id: "+1868", code: "+1868", name: "Trinidad and Tobago", flag: "🇹🇹" },
    { id: "+216", code: "+216", name: "Tunisia", flag: "🇹🇳" },
    { id: "+90", code: "+90", name: "Turkey", flag: "🇹🇷" },
    { id: "+993", code: "+993", name: "Turkmenistan", flag: "🇹🇲" },
    { id: "+1", code: "+1", name: "Turks and Caicos Islands", flag: "🇹🇨" },
    { id: "+688", code: "+688", name: "Tuvalu", flag: "🇹🇻" },
    { id: "+256", code: "+256", name: "Uganda", flag: "🇺🇬" },
    { id: "+380", code: "+380", name: "Ukraine", flag: "🇺🇦" },
    { id: "+971", code: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
    { id: "+44", code: "+44", name: "United Kingdom", flag: "🇬🇧" },
    { id: "+1", code: "+1", name: "United States", flag: "🇺🇸" },
    { id: "+598", code: "+598", name: "Uruguay", flag: "🇺🇾" },
    { id: "+998", code: "+998", name: "Uzbekistan", flag: "🇺🇿" },
    { id: "+678", code: "+678", name: "Vanuatu", flag: "🇻🇺" },
    { id: "+379", code: "+379", name: "Vatican City", flag: "🇻🇦" },
    { id: "+58", code: "+58", name: "Venezuela", flag: "🇻🇪" },
    { id: "+84", code: "+84", name: "Vietnam", flag: "🇻🇳" },
    { id: "+1", code: "+1", name: "Wallis and Futuna", flag: "🇼🇫" },
    { id: "+967", code: "+967", name: "Yemen", flag: "🇾🇪" },
    { id: "+260", code: "+260", name: "Zambia", flag: "🇿🇲" },
    { id: "+263", code: "+263", name: "Zimbabwe", flag: "🇿🇼" },
  ];