name: Storybook Preview

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Debug workspace
        run: |
          pwd
          ls -lah
          cat pnpm-workspace.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Install netiploy
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/systatum/netiploy/main/install.sh \
            | bash

      - name: Compute deployment subfolder
        id: deploy
        run: |
          SUBFOLDER="${GITHUB_REF_NAME}"
          SAFE_SUBFOLDER=$(echo "$SUBFOLDER" | tr '/' '-')
          echo "subfolder=$SAFE_SUBFOLDER" >> $GITHUB_OUTPUT

      - name: Deploy to R2
        run: |
          netiploy deploy storybook-static to r2/systatum-dev/coneto \
            --subfolder=hash:${{ steps.deploy.outputs.subfolder }} \
            --token="${{ secrets.R2_ACCESS_KEY_ID }}:${{ secrets.R2_SECRET_ACCESS_KEY }}"
